### ISSUE TITLE
LED Issue

### ISSUE THREAD

**Issue by Kevlar316** [TechBubbleTechnologies/IoT-JumpWay-RPI-Examples#5]
Hola, I have followed the guide up to the run applications part and on the Basic-LED-Device.py I am getting an error, when running it says:

Traceback (most recent call last):
     File "/home/kevlar/iotjumpway/IoT-JumpWay-RPI-Examples/Basic-LED/Python/Basic-LED-Device.py", line 80, in <module>
         BasicLED = BasicLED()
     File "/home/kevlar/iotjumpway/IoT-JumpWay-RPI-Examples/Basic-LED/Python/Basic-LED-Device.py", line 33, in __init__
         self:configs["Sensors"] ["LED"] ["Pin"],
KeyError: 'LED'

I'm not sure what this means or how to fix so any help is appreciated :-)
Thanks

**Comment by AdamMiltonBarker** [comment]
Hi @Kevlar316  thanks for sending through an issue. 

In Python this means that  the key "LED" does not exist in Sensors array which is correct in the example, as an LED is an Actuator. The error you receive is due to a code error on our side and I will update the code ASAP, for now to solve your issue you can change ["Sensors"] ["LED"] ["Pin"] to ["Actuators"] ["LED"] ["Pin"] in line 33 of  Basic-LED-Device.py and make sure you have added your LED details etc to the configs and all should work.

**Comment by Kevlar316** [comment]
Thanks for this, that error has now gone. Now I have a new error that says:

Traceback (most recent call last):
     File "/home/kevlar/iotjumpway/IoT-JumpWay-RPI-Examples/Basic-LED/Python/Basic-LED-Device.py", line 80, in <module>
         BasicLED = BasicLED()
     File "/home/kevlar/iotjumpway/IoT-JumpWay-RPI-Examples/Basic-LED/Python/Basic-LED-Device.py", line 34, in __init__
         GPIO.OUT
RunTimeError: No access to /dev/mem. Try running as root!

All fun and games, thanks for the help :-)

**Comment by AdamMiltonBarker** [comment]
No problem, if you run as shown in the tutorial:

`sudo python/python3 Basic-Led-Device.py`

**sudo** is running as root.

**Comment by Kevlar316** [comment]
Whoops, should of gone back to the guide ;-)

**Comment by AdamMiltonBarker** [comment]
No problem ;) Let me know if any more issues mate.

**Comment by Kevlar316** [comment]
This is all fixed now thanks for the help and please close the ticket.

**Comment by AdamMiltonBarker** [comment]
No problem
